version: "2"
services:
    mysql:
      build:
        context: 'phpdocker/mysql'
        dockerfile: Dockerfile
      container_name: umi-mysql
      working_dir: /var/lib/mysql
      # command: mysqld --sql_mode=""
      volumes:
        - ./app/db/mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=pass
        - MYSQL_DATABASE=db
      ports:
        - "13306:3306"
      restart: always
    webserver:
      image: nginx:alpine
      container_name: umi-webserver
      working_dir: /var/www/html/web
      volumes:
        - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./app/nginx/log:/var/log/nginx
      ports:
        - "3333:3333"
      depends_on:
        - php
      volumes_from:
        - php
    php:
      build: phpdocker/php-fpm
      container_name: umi-php-fpm
      working_dir: /var/www/html/web/umi
      volumes:
        - ./../umi:/var/www/html/web/umi
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
        - ./../phpmyadmin:/var/www/html/web/phpmyadmin
      depends_on:
        - mysql
      environment:
        PHP_EXTENSION_XDEBUG: 1
        XDEBUG_CONFIG: "remote_enable=1 remote_port=9002 remote_host=192.168.0.9 remote_connect_back=0 remote_autostart=1 var_display_max_data=1024 var_display_max_depth=5"
        PHP_IDE_CONFIG: "serverName=dock-debug-server-umi"